### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by dreaganluna** [rscherf/GitLink#4]
Traceback (most recent call last):
  File "C:\Users\[userName]\progs\Sublime Text 3\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "GitLink in C:\Users\[userName]\progs\Sublime Text 3\Data\Installed Packages\GitLink.sublime-package", line 44, in run
IndexError: list index out of range

none of the functionality seems to work

**Comment by fredericosilva** [comment]
Same problem here with ST3 build 3083

**Comment by rscherf** [comment]
I think this has been broken for awhile. Looks like you're both on Windows, which is a platform I don't have. I'm happy to entertain any pull requests to fix this.

**Comment by Kristinita** [comment]
@fredericosilva , problem not fixed for me. I click right mouse button to name any file of my local repository → `GitLink` → `Open Git URL to file `→ I get stack trace:

```python
command: gitlink {"line": false, "web": true}
Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "GitLink in E:\Sublime Text 3\Data\Installed Packages\GitLink.sublime-package", line 50, in run
IndexError: list index out of range
```

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.
